export const severityLabels = {
  CRITICAL: "Critica",
  HIGH: "Alta",
  MEDIUM: "Media",
  LOW: "Baixa",
};

export const statusLabels = {
  DRAFT: "Rascunho",
  IN_REVIEW: "Em analise",
  PUBLISHED: "Publicado",
  IGNORED: "Ignorado",
};

export const frequencyLabels = {
  HOURLY: "Horaria",
  DAILY: "Diaria",
  WEEKLY: "Semanal",
  MANUAL: "Manual",
};

function hashFrom(id) {
  return id.replace(/[^a-z0-9]/gi, "").slice(0, 6).padEnd(6, "0").toLowerCase();
}

function source({
  id,
  name,
  agency,
  uf = null,
  category,
  documents,
  url,
  frequency = "DAILY",
  severity = "MEDIUM",
  mode = "HTML_TEXT",
  checked = "2026-07-07T07:00:00-03:00",
}) {
  return {
    id,
    name,
    agency,
    uf,
    category,
    documents,
    url,
    frequency,
    severity,
    mode,
    active: true,
    lastCheckedAt: checked,
    lastHash: hashFrom(id),
  };
}

const nationalSources = [
  source({
    id: "nfe-portal",
    name: "NF-e/NFC-e - Portal Nacional",
    agency: "Portal Nacional NF-e",
    category: "NACIONAL",
    documents: ["NF-e", "NFC-e"],
    url: "https://www.nfe.fazenda.gov.br/portal/principal.aspx",
    frequency: "HOURLY",
    severity: "HIGH",
    checked: "2026-07-07T16:00:00-03:00",
  }),
  source({
    id: "nfe-notas-tecnicas",
    name: "NF-e/NFC-e - Notas Tecnicas",
    agency: "Portal Nacional NF-e",
    category: "NACIONAL",
    documents: ["NF-e", "NFC-e"],
    url: "https://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=04BIflQt1aY%3D",
    frequency: "HOURLY",
    severity: "CRITICAL",
    checked: "2026-07-07T16:08:00-03:00",
  }),
  source({
    id: "nfe-esquemas-xml",
    name: "NF-e - Esquemas XML",
    agency: "Portal Nacional NF-e",
    category: "NACIONAL",
    documents: ["NF-e", "DF-e", "Distribuicao DF-e", "XML"],
    url: "https://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=BMPFMBoln3w%3D",
    frequency: "HOURLY",
    severity: "CRITICAL",
    checked: "2026-07-10T09:20:00-03:00",
  }),
  source({
    id: "cte-portal",
    name: "CT-e - Portal Nacional",
    agency: "Portal Nacional CT-e",
    category: "NACIONAL",
    documents: ["CT-e", "CT-e OS", "GTV-e"],
    url: "https://www.cte.fazenda.gov.br/portal/",
    frequency: "HOURLY",
    severity: "HIGH",
    checked: "2026-07-07T15:50:00-03:00",
  }),
  source({
    id: "cte-notas-tecnicas",
    name: "CT-e - Notas Tecnicas",
    agency: "Portal Nacional CT-e",
    category: "NACIONAL",
    documents: ["CT-e", "CT-e OS"],
    url: "https://www.cte.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=Y0nErnoZpsg%3D",
    frequency: "HOURLY",
    severity: "HIGH",
    checked: "2026-07-07T15:48:00-03:00",
  }),
  source({
    id: "mdfe-svrs",
    name: "MDF-e - SVRS",
    agency: "SVRS",
    category: "NACIONAL",
    documents: ["MDF-e"],
    url: "https://dfe-portal.svrs.rs.gov.br/Mdfe",
    frequency: "HOURLY",
    severity: "HIGH",
    checked: "2026-07-07T16:05:00-03:00",
  }),
  source({
    id: "mdfe-documentos",
    name: "MDF-e - Documentos",
    agency: "SVRS",
    category: "NACIONAL",
    documents: ["MDF-e"],
    url: "https://dfe-portal.svrs.rs.gov.br/Mdfe/Documentos",
    frequency: "HOURLY",
    severity: "HIGH",
    checked: "2026-07-07T15:40:00-03:00",
  }),
  source({
    id: "dfe-svrs",
    name: "Portal DF-e SVRS",
    agency: "SVRS",
    category: "NACIONAL",
    documents: ["DF-e"],
    url: "https://dfe-portal.svrs.rs.gov.br/",
  }),
  source({
    id: "nfse-nacional",
    name: "NFS-e Nacional",
    agency: "Gov.br NFS-e",
    category: "NACIONAL",
    documents: ["NFS-e"],
    url: "https://www.gov.br/nfse/pt-br",
    severity: "HIGH",
  }),
  source({
    id: "nfse-documentacao",
    name: "NFS-e - Documentacao Tecnica",
    agency: "Gov.br NFS-e",
    category: "NACIONAL",
    documents: ["NFS-e"],
    url: "https://www.gov.br/nfse/pt-br/biblioteca/documentacao-tecnica",
    severity: "HIGH",
  }),
  source({
    id: "receita-reforma-tributaria",
    name: "Receita - Reforma Tributaria do Consumo",
    agency: "Receita Federal",
    category: "NACIONAL",
    documents: ["Todos"],
    url: "https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/acoes-e-programas/programas-e-atividades/reforma-tributaria-do-consumo",
    severity: "HIGH",
  }),
  source({
    id: "receita-orientacoes-2026",
    name: "Receita - Orientacoes 2026",
    agency: "Receita Federal",
    category: "NACIONAL",
    documents: ["Todos"],
    url: "https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/acoes-e-programas/programas-e-atividades/reforma-tributaria-do-consumo/orientacoes-2026",
    severity: "HIGH",
  }),
  source({
    id: "receita-cnpj-alfanumerico",
    name: "Receita - CNPJ Alfanumerico",
    agency: "Receita Federal",
    category: "NACIONAL",
    documents: ["Cadastros", "XML", "Integracoes"],
    url: "https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/acoes-e-programas/programas-e-atividades/cnpj-alfanumerico",
    severity: "HIGH",
  }),
  source({
    id: "confaz-ajustes-sinief",
    name: "CONFAZ - Ajustes SINIEF",
    agency: "CONFAZ",
    category: "NACIONAL",
    documents: ["DF-e"],
    url: "https://www.confaz.fazenda.gov.br/legislacao/ajustes",
    severity: "HIGH",
  }),
  source({
    id: "confaz-convenios-icms",
    name: "CONFAZ - Convenios ICMS",
    agency: "CONFAZ",
    category: "NACIONAL",
    documents: ["ICMS", "Beneficios"],
    url: "https://www.confaz.fazenda.gov.br/legislacao/convenios",
  }),
  source({
    id: "sped-portal",
    name: "Portal SPED",
    agency: "SPED",
    category: "OBRIGACAO_ACESSORIA",
    documents: ["SPED Fiscal"],
    url: "https://www.gov.br/sped/pt-br",
  }),
  source({
    id: "efd-icms-ipi",
    name: "EFD ICMS/IPI",
    agency: "SPED",
    category: "OBRIGACAO_ACESSORIA",
    documents: ["SPED Fiscal"],
    url: "https://www.gov.br/sped/pt-br/assuntos/escrituracao-fiscal-digital-efd",
  }),
  source({
    id: "nfcom-receita",
    name: "NFCom - Receita Federal",
    agency: "Receita Federal",
    category: "NACIONAL",
    documents: ["NFCom"],
    url: "https://www.gov.br/receitafederal/pt-br/assuntos/empresas-e-negocios/dfe/nfcom",
    frequency: "WEEKLY",
  }),
  source({
    id: "nfcom-svrs-documentos",
    name: "NFCom - Documentos SVRS",
    agency: "SVRS",
    category: "NACIONAL",
    documents: ["NFCom", "DF-e", "RTC"],
    url: "https://dfe-portal.svrs.rs.gov.br/Nfcom/Documentos",
    severity: "HIGH",
  }),
  source({
    id: "bpe-svrs-documentos",
    name: "BP-e - Documentos SVRS",
    agency: "SVRS",
    category: "NACIONAL",
    documents: ["BP-e", "DF-e", "RTC"],
    url: "https://dfe-portal.svrs.rs.gov.br/Bpe/Documentos",
    severity: "HIGH",
  }),
  source({
    id: "nf3e-svrs-documentos",
    name: "NF3e - Documentos SVRS",
    agency: "SVRS",
    category: "NACIONAL",
    documents: ["NF3e", "DF-e", "RTC"],
    url: "https://dfe-portal.svrs.rs.gov.br/Nf3e/Documentos",
    severity: "HIGH",
  }),
  source({
    id: "nfag-svrs-documentos",
    name: "NFAg - Documentos SVRS",
    agency: "SVRS",
    category: "NACIONAL",
    documents: ["NFAg", "DF-e", "RTC"],
    url: "https://dfe-portal.svrs.rs.gov.br/Nfag/Documentos",
    severity: "HIGH",
  }),
  source({
    id: "nfgas-svrs-documentos",
    name: "NFGas - Documentos SVRS",
    agency: "SVRS",
    category: "NACIONAL",
    documents: ["NFGas", "DF-e", "RTC"],
    url: "https://dfe-portal.svrs.rs.gov.br/Nfgas/Documentos",
    severity: "HIGH",
  }),
];

const stateRows = [
  ["sefaz-ac", "SEFAZ Acre - DF-e", "SEFAZ Acre", "AC", ["DF-e"], "https://dfe.sefaz.ac.gov.br/"],
  ["sefaz-al", "SEFAZ Alagoas - Contribuinte", "SEFAZ Alagoas", "AL", ["DF-e", "ICMS"], "https://contribuinte.sefaz.al.gov.br/"],
  ["sefaz-ap", "SEFAZ Amapa - Documentos Fiscais", "SEFAZ Amapa", "AP", ["NF-e", "NFC-e", "CT-e", "MDF-e", "EFD"], "https://www.sefaz.ap.gov.br/"],
  ["sefaz-am", "SEFAZ Amazonas - NF-e", "SEFAZ Amazonas", "AM", ["NF-e"], "https://sistemas.sefaz.am.gov.br/nfeweb/portal/index.do"],
  ["sefaz-ba", "SEFAZ Bahia - NF-e", "SEFAZ Bahia", "BA", ["NF-e"], "https://www.sefaz.ba.gov.br/inspetoria-eletronica/icms/documentos-fiscais/nota-fiscal-eletronica/"],
  ["sefaz-ce", "SEFAZ Ceara - NF-e/NFC-e", "SEFAZ Ceara", "CE", ["NF-e", "NFC-e"], "https://nfe.sefaz.ce.gov.br/pages/index.jsf"],
  ["receita-df", "Receita DF - Carta de Servicos", "Receita DF", "DF", ["DF-e"], "https://www.receita.fazenda.df.gov.br/aplicacoes/CartaServicos/"],
  ["sefaz-es", "SEFAZ Espirito Santo - NF-e", "SEFAZ Espirito Santo", "ES", ["NF-e"], "https://sefaz.es.gov.br/nfe-nota-fiscal-eletronica"],
  ["sefaz-go", "Economia Goias - NF-e", "Economia Goias", "GO", ["NF-e", "NFC-e", "CT-e", "XML"], "https://nfe.sefaz.go.gov.br/nfeweb/portal/index.jsp"],
  ["sefaz-ma", "SEFAZ Maranhao - Plataforma", "SEFAZ Maranhao", "MA", ["DF-e"], "https://plataforma.sefaz.ma.gov.br/"],
  ["sefaz-mt", "SEFAZ Mato Grosso - NF-e", "SEFAZ Mato Grosso", "MT", ["NF-e"], "https://www.sefaz.mt.gov.br/portal/nfe/"],
  ["sefaz-ms", "SEFAZ Mato Grosso do Sul - NF-e", "SEFAZ Mato Grosso do Sul", "MS", ["NF-e"], "https://www.nfe.ms.gov.br/"],
  ["sefaz-mg", "SEF Minas Gerais - Documentos Fiscais", "SEF Minas Gerais", "MG", ["NF-e", "DF-e"], "https://www.fazenda.mg.gov.br/empresas/documentos_fiscais/"],
  ["sefa-pa", "SEFA Para - Servicos", "SEFA Para", "PA", ["DF-e"], "https://app.sefa.pa.gov.br/pservicos/"],
  ["sefaz-pb", "SEFAZ Paraiba - NF-e", "SEFAZ Paraiba", "PB", ["NF-e"], "https://www.sefaz.pb.gov.br/info/notas-fiscais/nf-e"],
  ["sefaz-pr", "Fazenda Parana - NF-e", "Fazenda Parana", "PR", ["NF-e"], "https://sped.fazenda.pr.gov.br/NFe"],
  ["sefaz-pe", "SEFAZ Pernambuco - Documentos Fiscais", "SEFAZ Pernambuco", "PE", ["NF-e", "DF-e"], "https://www.sefaz.pe.gov.br/Servicos/ICMS/Paginas/Documentos_Fiscais.aspx"],
  ["sefaz-pi", "SEFAZ Piaui - Documentos Eletronicos", "SEFAZ Piaui", "PI", ["NF-e", "NFC-e", "CT-e", "MDF-e", "EFD"], "https://portal.sefaz.pi.gov.br/conteudos-institucional%2Bdocumentos-eletronicos%2B69d6979dc41c7a09017fa749"],
  ["sefaz-rj", "SEFAZ Rio de Janeiro - DF-e", "SEFAZ Rio de Janeiro", "RJ", ["DF-e", "Beneficios"], "https://portal.fazenda.rj.gov.br/dfe/"],
  ["sefaz-rn", "SEFAZ Rio Grande do Norte - Documentos Eletronicos", "SEFAZ Rio Grande do Norte", "RN", ["NF-e", "NFC-e", "CT-e", "BP-e", "MDF-e", "NFA", "EFD"], "https://www.sefaz.rn.gov.br/postagem/documentos-eletronicos/"],
  ["sefaz-rs", "SEFAZ RS / SVRS - DF-e", "SEFAZ RS / SVRS", "RS", ["DF-e"], "https://dfe-portal.svrs.rs.gov.br/", "HOURLY", "HIGH"],
  ["sefin-ro", "SEFIN Rondonia - NF-e", "SEFIN Rondonia", "RO", ["NF-e"], "https://www.sefin.ro.gov.br/conteudo.jsp?idCategoria=524"],
  ["sefaz-rr", "SEFAZ Roraima - Portal", "SEFAZ Roraima", "RR", ["DF-e"], "https://www.sefaz.rr.gov.br/"],
  ["sefaz-sc", "SEF Santa Catarina - NF-e", "SEF Santa Catarina", "SC", ["NF-e", "NFC-e"], "https://www.sef.sc.gov.br/servicos/servico/62/NF-e_-_Nota_Fiscal_Eletr%25C3%25B4nica"],
  ["sefaz-sp-cbenef", "SEFAZ Sao Paulo - cBenef", "SEFAZ Sao Paulo", "SP", ["NF-e", "NFC-e"], "https://portal.fazenda.sp.gov.br/servicos/nfe/Paginas/cBenef.aspx", "HOURLY", "HIGH"],
  ["sefaz-se", "SEFAZ Sergipe - Servicos Online", "SEFAZ Sergipe", "SE", ["DF-e"], "https://www.sefaz.se.gov.br/SitePages/servicos-online.aspx"],
  ["sefaz-to", "SEFAZ Tocantins - Documentos Fiscais Eletronicos", "SEFAZ Tocantins", "TO", ["DF-e", "EFD"], "https://www.to.gov.br/sefaz/documentos-fiscais-eletronicos/2fowj6ej5zil"],
];

const stateSources = stateRows.map(
  ([id, name, agency, uf, documents, url, frequency = "DAILY", severity = "MEDIUM"], index) =>
    source({
      id,
      name,
      agency,
      uf,
      category: "ESTADUAL",
      documents,
      url,
      frequency,
      severity,
      checked: `2026-07-07T${String(6 + Math.floor(index / 2)).padStart(2, "0")}:${String(
        (index * 7) % 60,
      ).padStart(2, "0")}:00-03:00`,
    }),
);

export const sourceSeed = [...nationalSources, ...stateSources];

const retroactiveChanges = [
  {
    id: "chg-nfse-danfse-nt008-101",
    sourceId: "nfse-documentacao",
    title: "DANFSe NT 008 v1.01 prorroga API antiga",
    protocol: "2026/0115",
    detectedAt: "2026-07-10T10:40:00-03:00",
    publicationDate: "2026-06-30",
    homologationDate: "2026-06-30",
    productionDate: "2026-07-15",
    effectiveDate: "2026-07-15",
    area: "Desenvolvimento",
    evidence: "nt-008-se-cgnfse-danfse-20260630-v1-01.pdf",
    evidenceUrl:
      "https://www.gov.br/nfse/pt-br/biblioteca/documentacao-tecnica/rtc/nt-008-se-cgnfse-danfse-20260630-v1-01.pdf",
    severity: "CRITICAL",
    status: "IN_REVIEW",
    theme: "DANFSe",
    uf: null,
    documents: ["NFS-e", "DANFSe"],
    confidence: 95,
    summary:
      "A NFS-e publicou a versao 1.01 da NT 008 e prorrogou a descontinuacao da API antiga de geracao do DANFSe para 15/07/2026.",
    impact:
      "ERPs e emissores que dependem da API antiga de DANFSe precisam ajustar layout, impressao e integracao antes do corte.",
    action:
      "Validar geracao do DANFSe pelo novo leiaute, testar emissao em homologacao e comunicar clientes que usam representacao impressa.",
    changedExcerpt:
      "Versao 1.01 da NT 008 altera o prazo de descontinuacao da API atual do DANFSe para 15/07/2026.",
    diffBefore: "API antiga de DANFSe prevista para ser descontinuada em 01/07/2026.",
    diffAfter: "Prazo prorrogado para 15/07/2026, mantendo necessidade de adequacao tecnica.",
  },
  {
    id: "chg-nfse-nt009-rtc",
    sourceId: "nfse-documentacao",
    title: "NFS-e NT 009 consolida evolucoes RTC",
    protocol: "2026/0109",
    detectedAt: "2026-07-10T10:35:00-03:00",
    publicationDate: "2026-06-09",
    homologationDate: "2026-06-09",
    productionDate: "",
    effectiveDate: "",
    area: "Produto",
    evidence: "nt-009-se-cgnfse-v1-0-1.pdf",
    evidenceUrl:
      "https://www.gov.br/nfse/pt-br/biblioteca/documentacao-tecnica/rtc/nt-009-se-cgnfse-v1-0-1.pdf",
    severity: "HIGH",
    status: "IN_REVIEW",
    theme: "Reforma Tributaria",
    uf: null,
    documents: ["NFS-e", "RTC"],
    confidence: 90,
    summary:
      "A NT 009 da NFS-e consolida adaptacoes no layout da DPS e da NFS-e para a Reforma Tributaria do Consumo.",
    impact:
      "Pode exigir revisao de campos, regras de negocio, validacoes e mapeamento fiscal de IBS/CBS nos modulos de servicos.",
    action:
      "Comparar anexos da NT 009 com o layout em uso e abrir backlog para campos e regras alteradas.",
    changedExcerpt:
      "NT 009 informa evolucoes na DPS e na NFS-e gerada, incluindo adequacoes ao CNPJ alfanumerico e a RTC.",
    diffBefore: "Layout RTC acompanhado pelas NTs anteriores da NFS-e.",
    diffAfter: "NT 009 consolida novas adaptacoes da DPS e do documento NFS-e.",
  },
  {
    id: "chg-nfse-simples-emissor-nacional",
    sourceId: "nfse-nacional",
    title: "Simples Nacional deve usar Emissor Nacional NFS-e",
    protocol: "2026/0901",
    detectedAt: "2026-07-10T10:30:00-03:00",
    publicationDate: "2026-04-28",
    homologationDate: "2026-07-01",
    productionDate: "2026-09-01",
    effectiveDate: "2026-09-01",
    area: "Fiscal",
    evidence: "",
    severity: "HIGH",
    status: "IN_REVIEW",
    theme: "Obrigatoriedade",
    uf: null,
    documents: ["NFS-e", "Simples Nacional"],
    confidence: 91,
    summary:
      "ME e EPP optantes pelo Simples Nacional passam a ter obrigatoriedade de emissao pelo Emissor Nacional da NFS-e a partir de 01/09/2026.",
    impact:
      "Afeta onboarding, suporte, parametrizacao municipal e orientacao a clientes prestadores de servicos optantes pelo Simples.",
    action:
      "Preparar comunicacao, revisar integrações com municipios e mapear clientes optantes pelo Simples Nacional.",
    changedExcerpt:
      "Obrigatoriedade do Emissor Nacional da NFS-e para optantes do Simples Nacional com vigencia em 01/09/2026.",
    diffBefore: "Uso do Emissor Nacional dependia do municipio/convenio e do cenario do contribuinte.",
    diffAfter: "Obrigatoriedade nacional para ME/EPP do Simples Nacional a partir de setembro de 2026.",
  },
  {
    id: "chg-receita-cnpj-alfanumerico-julho",
    sourceId: "receita-cnpj-alfanumerico",
    title: "CNPJ alfanumerico entra para novas inscricoes",
    protocol: "2026/0701",
    detectedAt: "2026-07-10T10:25:00-03:00",
    publicationDate: "2024-10-15",
    homologationDate: "2026-06-15",
    productionDate: "2026-07-01",
    effectiveDate: "2026-07-01",
    area: "Desenvolvimento",
    evidence: "",
    severity: "CRITICAL",
    status: "IN_REVIEW",
    theme: "CNPJ Alfanumerico",
    uf: null,
    documents: ["Cadastros", "Integracoes", "XML"],
    confidence: 95,
    summary:
      "A Receita informa que o CNPJ alfanumerico passa a ser atribuido a novas inscricoes a partir de julho de 2026.",
    impact:
      "Qualquer validacao numerica de CNPJ, mascara, banco, importacao, API ou schema XML pode rejeitar novos cadastros.",
    action:
      "Auditar validadores, campos, integrações, relatórios, importadores e regras fiscais que assumem CNPJ apenas numerico.",
    changedExcerpt:
      "CNPJ alfanumerico sera atribuido, a partir de julho de 2026, exclusivamente a novas inscricoes.",
    diffBefore: "Novas inscricoes usavam CNPJ numerico tradicional.",
    diffAfter: "Novas inscricoes podem receber identificador alfanumerico sem alterar CNPJs ja existentes.",
  },
  {
    id: "chg-receita-rtc-obrigacoes-2026",
    sourceId: "receita-orientacoes-2026",
    title: "Obrigacoes RTC 2026 para documentos fiscais",
    protocol: "2026/0001",
    detectedAt: "2026-07-10T10:20:00-03:00",
    publicationDate: "2025-12-12",
    homologationDate: "2025-12-10",
    productionDate: "2026-01-01",
    effectiveDate: "2026-01-01",
    area: "Produto",
    evidence: "",
    severity: "HIGH",
    status: "PUBLISHED",
    theme: "Reforma Tributaria",
    uf: null,
    documents: ["Todos", "RTC"],
    confidence: 92,
    summary:
      "A Receita orienta que, desde 01/01/2026, documentos fiscais eletronicos devem destacar CBS e IBS conforme notas tecnicas especificas.",
    impact:
      "Serve como base retroativa para priorizar todos os leiautes de NF-e, NFC-e, CT-e, NFS-e, NFCom, NF3e e BP-e ligados a RTC.",
    action:
      "Manter trilha de adequacao por documento fiscal e cruzar cada NT com modulo, cliente e data de vigencia.",
    changedExcerpt:
      "A partir de 1 de janeiro de 2026, documentos fiscais eletronicos devem ser emitidos com destaque da CBS e do IBS.",
    diffBefore: "Documentos fiscais sem campos obrigatorios de CBS/IBS no periodo anterior.",
    diffAfter: "Ano de teste da CBS/IBS com obrigacoes acessorias definidas por notas tecnicas.",
  },
  {
    id: "chg-nfe-nt-2014-002-140",
    sourceId: "nfe-notas-tecnicas",
    title: "NT 2014.002 v1.40 atualiza distribuicao DF-e",
    protocol: "2026/0140",
    detectedAt: "2026-07-10T10:15:00-03:00",
    publicationDate: "2026-07-03",
    homologationDate: "2026-07-03",
    productionDate: "2026-07-03",
    effectiveDate: "2026-07-03",
    area: "Desenvolvimento",
    evidence: "nt_2014_002_v140_distribuicao_dfe.pdf",
    evidenceUrl:
      "https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=uWO2d%2FgTuWg%3D",
    severity: "CRITICAL",
    status: "IN_REVIEW",
    theme: "Distribuicao DF-e",
    uf: null,
    documents: ["DF-e", "Distribuicao DF-e", "NF-e"],
    confidence: 95,
    summary:
      "O Portal NF-e publicou a NT 2014.002 v1.40 do Web Service de distribuicao de documentos fiscais eletronicos.",
    impact:
      "Pode afetar consumo por NSU, manifestacao, download de XML, armazenamento de eventos e integracoes de consulta automatizada.",
    action:
      "Comparar a NT v1.40 com a implementacao atual do NFeDistribuicaoDFe e validar impactos junto ao pacote de schemas v1.04.",
    changedExcerpt:
      "Nota Tecnica 2014.002 v1.40 publicada em 03/07/2026 para Web Service de distribuicao de documentos fiscais eletronicos.",
    diffBefore: "Monitor considerava pacote de schemas, mas nao a nota tecnica retroativa que rege o servico.",
    diffAfter: "NT v1.40 passa a compor a previsao de impacto da distribuicao DF-e.",
  },
  {
    id: "chg-nfe-nt-2026-001-paa",
    sourceId: "nfe-notas-tecnicas",
    title: "NF-e NT 2026.001 v1.02a consolida PAA",
    protocol: "2026/0101",
    detectedAt: "2026-07-10T10:10:00-03:00",
    publicationDate: "2026-06-23",
    homologationDate: "",
    productionDate: "",
    effectiveDate: "",
    area: "Desenvolvimento",
    evidence: "nt_2026_001_v102a_paa.pdf",
    evidenceUrl:
      "https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=17%2F3gkpGzPY%3D",
    severity: "HIGH",
    status: "IN_REVIEW",
    theme: "PAA",
    uf: null,
    documents: ["NF-e", "NFC-e", "PAA"],
    confidence: 88,
    summary:
      "A NT 2026.001 v1.02a da NF-e/NFC-e deve ser acompanhada para regras ligadas ao Provedor de Assinatura e Autorizacao.",
    impact:
      "Pode alterar fluxos de contingencia, assinatura/autorizacao e validacoes de integradores que usam PAA.",
    action:
      "Revisar escopo do PAA, impactos de autorizacao e necessidade de ajustes em ambientes de emissao.",
    changedExcerpt:
      "Nota Tecnica 2026.001 v1.02a publicada em 23/06/2026 no Portal Nacional NF-e.",
    diffBefore: "Versoes anteriores da NT 2026.001 sem consolidacao v1.02a.",
    diffAfter: "Versao v1.02a entra no backlog retroativo de analise.",
  },
  {
    id: "chg-nfe-cnpj-alfanum-nt-2026-004",
    sourceId: "nfe-notas-tecnicas",
    title: "NF-e NT 2026.004 v1.01 ajusta CNPJ alfanumerico",
    protocol: "2026/0401",
    detectedAt: "2026-07-10T10:05:00-03:00",
    publicationDate: "2026-06-08",
    homologationDate: "2026-06-15",
    productionDate: "2026-07-01",
    effectiveDate: "2026-07-01",
    area: "Desenvolvimento",
    evidence: "nt_2026_004_v101_cnpj_alfanumerico.pdf",
    evidenceUrl:
      "https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=BTZQzgsO9Ws%3D",
    severity: "CRITICAL",
    status: "IN_REVIEW",
    theme: "CNPJ Alfanumerico",
    uf: null,
    documents: ["NF-e", "NFC-e", "XML", "Cadastros"],
    confidence: 94,
    summary:
      "A NT 2026.004 v1.01 atualiza schemas e regras da NF-e/NFC-e para suportar CNPJ alfanumerico.",
    impact:
      "Afeta tags XML, validadores, cadastro de emitente/destinatario, consultas e integracoes que tratam CNPJ como numerico.",
    action:
      "Baixar NT e schemas 010d, rodar validacao de XML e revisar bibliotecas de CNPJ antes de aceitar novas inscricoes.",
    changedExcerpt:
      "Atualizacao do schema da NF-e/NFC-e para adequacao ao CNPJ alfanumerico.",
    diffBefore: "Schemas e validadores baseados em CNPJ numerico.",
    diffAfter: "Schemas e regras passam a contemplar CNPJ alfanumerico para novas inscricoes.",
  },
  {
    id: "chg-nfe-rtc-2025-002-150",
    sourceId: "nfe-notas-tecnicas",
    title: "NF-e/NFC-e NT 2025.002 v1.50 RTC",
    protocol: "2026/0150",
    detectedAt: "2026-07-10T10:00:00-03:00",
    publicationDate: "2026-06-03",
    homologationDate: "2025-12-10",
    productionDate: "2026-01-01",
    effectiveDate: "2026-01-01",
    area: "Produto",
    evidence: "nt_2025_002_v150_rtc_nfe_nfce.pdf",
    evidenceUrl:
      "https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=pD4YrecPV6s%3D",
    severity: "CRITICAL",
    status: "IN_REVIEW",
    theme: "Reforma Tributaria",
    uf: null,
    documents: ["NF-e", "NFC-e", "RTC"],
    confidence: 93,
    summary:
      "A NT 2025.002 v1.50 atualiza o leiaute da NF-e/NFC-e para campos e regras de validacao da Reforma Tributaria do Consumo.",
    impact:
      "Afeta emissao, totalizadores, validacoes de IBS/CBS, DANFE, XML, testes regressivos e comunicacao fiscal.",
    action:
      "Conferir a versao v1.50 contra schemas 010e e mapear campos obrigatorios por produto e por regra fiscal.",
    changedExcerpt:
      "Adequacao dos leiautes da NF-e e NFC-e para inclusao de campos e regras de validacao da RTC.",
    diffBefore: "Backlog acompanhava versao generica da NT sem versao retroativa consolidada.",
    diffAfter: "NT 2025.002 v1.50 passa a ser a base de analise de RTC para NF-e/NFC-e.",
  },
  {
    id: "chg-nfe-nt-2026-003-danfe-simplificado",
    sourceId: "nfe-notas-tecnicas",
    title: "NF-e NT 2026.003 cria DANFE Simplificado Tipo 2",
    protocol: "2026/0300",
    detectedAt: "2026-07-10T09:55:00-03:00",
    publicationDate: "2026-05-25",
    homologationDate: "",
    productionDate: "",
    effectiveDate: "",
    area: "Desenvolvimento",
    evidence: "nt_2026_003_danfe_simplificado_tipo_2.pdf",
    evidenceUrl:
      "https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=2YdaBTIql%20k%3D",
    severity: "HIGH",
    status: "IN_REVIEW",
    theme: "DANFE",
    uf: null,
    documents: ["NF-e", "NFC-e", "DANFE"],
    confidence: 88,
    summary:
      "A NT 2026.003 trata do DANFE Simplificado Tipo 2 e pode exigir ajustes de impressao e representacao auxiliar.",
    impact:
      "Afeta layout de impressao, PDF, comprovantes, parametrizacao de clientes e testes de representacao da NF-e.",
    action:
      "Comparar especificacao do DANFE Tipo 2 com os modelos atuais e criar cenarios de impressao.",
    changedExcerpt:
      "Nota Tecnica 2026.003 v1.00 publicada em 25/05/2026 no Portal NF-e.",
    diffBefore: "DANFE tratado apenas pelos modelos anteriores.",
    diffAfter: "Novo tipo simplificado entra na fila de compatibilidade.",
  },
  {
    id: "chg-nfe-nt-2026-002-regra-modelo",
    sourceId: "nfe-notas-tecnicas",
    title: "NF-e NT 2026.002 altera regra de referencia modelo",
    protocol: "2026/0200",
    detectedAt: "2026-07-10T09:50:00-03:00",
    publicationDate: "2026-05-25",
    homologationDate: "",
    productionDate: "",
    effectiveDate: "",
    area: "Desenvolvimento",
    evidence: "nt_2026_002_nfe_regra_modelo_65_59.pdf",
    evidenceUrl:
      "https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=3v7VFvaogiA%3D",
    severity: "HIGH",
    status: "IN_REVIEW",
    theme: "Validacao fiscal",
    uf: null,
    documents: ["NF-e", "NFC-e", "CF-e"],
    confidence: 88,
    summary:
      "A NT 2026.002 cria regra de rejeicao para NF-e de saida que referencie NFC-e ou CF-e em determinados cenarios.",
    impact:
      "Pode bloquear emissao se o ERP permitir referencias cruzadas nao aceitas pela nova regra.",
    action:
      "Revisar validacoes de documentos referenciados antes do envio para autorizacao.",
    changedExcerpt:
      "Criação da regra BA02-35 que rejeita NF-e de saída com referência a modelo 65 ou 59.",
    diffBefore: "Validacao local podia aceitar referencias que passavam para a SEFAZ.",
    diffAfter: "Nova regra exige bloqueio ou orientacao antes do envio da NF-e.",
  },
  {
    id: "chg-nfe-it-2025-002-160-tabelas-rtc",
    sourceId: "nfe-notas-tecnicas",
    title: "IT 2025.002 v1.60 atualiza tabelas RTC",
    protocol: "2026/0160",
    detectedAt: "2026-07-10T09:45:00-03:00",
    publicationDate: "2026-06-23",
    homologationDate: "2026-06-23",
    productionDate: "2026-06-23",
    effectiveDate: "2026-06-23",
    area: "Fiscal",
    evidence: "it_2025_002_v160_tabelas_rtc.pdf",
    evidenceUrl:
      "https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=jxTMMQeEVM8%3D",
    severity: "HIGH",
    status: "IN_REVIEW",
    theme: "Tabelas fiscais",
    uf: null,
    documents: ["NF-e", "NFC-e", "RTC", "Tabelas"],
    confidence: 90,
    summary:
      "O Informe Tecnico 2025.002 v1.60 atualiza tabelas usadas na classificacao tributaria da RTC.",
    impact:
      "Pode alterar cClassTrib, CST, credito presumido e validacoes de cadastro/produto.",
    action:
      "Sincronizar tabelas oficiais, comparar codigos removidos/adicionados e preparar migracao de cadastros.",
    changedExcerpt:
      "Informe Tecnico 2025.002 v1.60 publicado em 23/06/2026.",
    diffBefore: "Tabelas RTC em versoes anteriores.",
    diffAfter: "Tabelas RTC atualizadas para a versao v1.60.",
  },
  {
    id: "chg-dfe-it-2026-001-split-meios-pagamento",
    sourceId: "dfe-svrs",
    title: "DF-e IT 2026.001 define meios de pagamento do Split",
    protocol: "2026/0601",
    detectedAt: "2026-07-10T09:40:00-03:00",
    publicationDate: "2026-05-12",
    homologationDate: "2026-05-12",
    productionDate: "2026-06-22",
    effectiveDate: "2026-06-22",
    area: "Produto",
    evidence: "",
    severity: "HIGH",
    status: "IN_REVIEW",
    theme: "Split Payment",
    uf: null,
    documents: ["DF-e", "CT-e", "BP-e", "NF3e", "NFCom", "NFAg", "NFGas"],
    confidence: 90,
    summary:
      "O IT 2026.001 orienta a tabela de meios de pagamento usada na vinculacao da transacao financeira ao DF-e para Split Payment.",
    impact:
      "Afeta mapeamento de meios de pagamento, eventos de vinculacao/cancelamento e integracoes de checkout/financeiro.",
    action:
      "Mapear codigos internos de pagamento para a tabela oficial e validar eventos de vinculacao nos documentos afetados.",
    changedExcerpt:
      "As NTs 2026.001 dos DFe introduzem grupo de vinculacao da transacao de pagamento ao documento fiscal.",
    diffBefore: "Meios de pagamento tratados por regras internas ou tabelas anteriores.",
    diffAfter: "Subset oficial de codigos passa a ser usado nos campos relacionados ao Split Payment.",
  },
  {
    id: "chg-cte-nt-2026-002-rtc",
    sourceId: "cte-notas-tecnicas",
    title: "CT-e NT 2026.002 evolui RTC",
    protocol: "2026/2602",
    detectedAt: "2026-07-10T09:35:00-03:00",
    publicationDate: "2026-06-10",
    homologationDate: "2026-06-29",
    productionDate: "",
    effectiveDate: "",
    area: "Desenvolvimento",
    evidence: "",
    severity: "HIGH",
    status: "IN_REVIEW",
    theme: "Reforma Tributaria",
    uf: null,
    documents: ["CT-e", "CT-e OS", "GTV-e", "RTC"],
    confidence: 89,
    summary:
      "A NT 2026.002 do CT-e traz evolucoes da RTC como antecipacao de pagamento, IBS/CBS, cashback e regras de validacao.",
    impact:
      "Afeta emissao de CT-e, CT-e OS e CT-e Simplificado, com reflexos em transporte, financeiro e XML.",
    action:
      "Comparar schemas de 29/06/2026 com os ambientes atuais e criar cenarios de transporte por modal.",
    changedExcerpt:
      "NT 2026.002 aplicavel a CTe, CTeOS e CTe Simplificado, com evolucoes da Reforma Tributaria.",
    diffBefore: "Adequacoes RTC baseadas na NT 2025.001.",
    diffAfter: "NT 2026.002 adiciona pontos de legislacao e regras de validacao.",
  },
  {
    id: "chg-cte-nt-2026-001-split",
    sourceId: "cte-notas-tecnicas",
    title: "CT-e NT 2026.001 vincula pagamento ao DFe",
    protocol: "2026/2601",
    detectedAt: "2026-07-10T09:30:00-03:00",
    publicationDate: "2026-03-02",
    homologationDate: "2026-05-12",
    productionDate: "2026-06-22",
    effectiveDate: "2026-06-22",
    area: "Desenvolvimento",
    evidence: "",
    severity: "HIGH",
    status: "IN_REVIEW",
    theme: "Split Payment",
    uf: null,
    documents: ["CT-e", "CT-e OS", "DF-e"],
    confidence: 90,
    summary:
      "A NT 2026.001 do CT-e detalha a vinculacao entre DF-e e transacao financeira para Split Payment.",
    impact:
      "Exige eventos/campos de vinculacao e cancelamento, codigos de meio de pagamento e revisao do fluxo financeiro.",
    action:
      "Validar schemas v1.01c, payloads de eventos e integracao com conciliacao financeira.",
    changedExcerpt:
      "Vinculacao entre DFe e transacao financeira sujeita ao split payment.",
    diffBefore: "CT-e sem grupo/evento padronizado para vinculo de pagamento RTC.",
    diffAfter: "Campos e eventos passam a informar a transacao financeira vinculada.",
  },
  {
    id: "chg-mdfe-nt-2026-001-ciot",
    sourceId: "mdfe-documentos",
    title: "MDF-e NT 2026.001 obriga CIOT em transporte remunerado",
    protocol: "2026/3001",
    detectedAt: "2026-07-10T09:25:00-03:00",
    publicationDate: "2026-05-29",
    homologationDate: "",
    productionDate: "",
    effectiveDate: "",
    area: "Fiscal",
    evidence: "",
    severity: "HIGH",
    status: "IN_REVIEW",
    theme: "CIOT",
    uf: null,
    documents: ["MDF-e", "CIOT"],
    confidence: 89,
    summary:
      "A NT 2026.001 do MDF-e cria regra de validacao obrigando CIOT para transporte rodoviario remunerado por conta de terceiros.",
    impact:
      "Pode gerar rejeicoes em MDF-e se o CIOT nao estiver informado conforme o Ajuste SINIEF 03/2026.",
    action:
      "Revisar cadastros de transporte, regras por tipo de operacao e validacao antes da autorizacao.",
    changedExcerpt:
      "Regra de validacao do MDF-e obrigando CIOT nas prestacoes de transporte rodoviario de cargas remuneradas.",
    diffBefore: "CIOT podia nao ser validado em todos os cenarios de transporte remunerado.",
    diffAfter: "Regra passa a exigir CIOT conforme Ajuste SINIEF 03/2026.",
  },
  {
    id: "chg-nfcom-nt-2026-002-rtc",
    sourceId: "nfcom-svrs-documentos",
    title: "NFCom NT 2026.002 evolui regras RTC",
    protocol: "2026/5602",
    detectedAt: "2026-07-10T09:20:00-03:00",
    publicationDate: "2026-06-10",
    homologationDate: "2026-06-29",
    productionDate: "",
    effectiveDate: "",
    area: "Produto",
    evidence: "",
    severity: "HIGH",
    status: "IN_REVIEW",
    theme: "Reforma Tributaria",
    uf: null,
    documents: ["NFCom", "RTC"],
    confidence: 89,
    summary:
      "A NFCom publicou a NT 2026.002 com evolucoes de RTC, incluindo antecipacao de pagamento, IBS/CBS, cashback e regras de validacao.",
    impact:
      "Afeta emissores de comunicacao/telecom, totalizadores, calculos e regras de validacao do documento.",
    action:
      "Comparar schemas RTC de 29/06/2026 e revisar cenarios de comunicacao com IBS/CBS.",
    changedExcerpt:
      "NT 2026.002 RTC v1.00 traz evolucoes da NT 2025.001 para NFCom.",
    diffBefore: "NFCom com adequacoes anteriores da NT 2025.001.",
    diffAfter: "NT 2026.002 adiciona novos pontos e regras da RTC.",
  },
  {
    id: "chg-nfcom-nt-2026-001-split",
    sourceId: "nfcom-svrs-documentos",
    title: "NFCom NT 2026.001 vincula pagamento ao DFe",
    protocol: "2026/5601",
    detectedAt: "2026-07-10T09:15:00-03:00",
    publicationDate: "2026-03-02",
    homologationDate: "2026-05-12",
    productionDate: "2026-06-22",
    effectiveDate: "2026-06-22",
    area: "Desenvolvimento",
    evidence: "",
    severity: "HIGH",
    status: "IN_REVIEW",
    theme: "Split Payment",
    uf: null,
    documents: ["NFCom", "DF-e", "Split Payment"],
    confidence: 89,
    summary:
      "A NFCom aderiu ao modelo de vinculacao entre DFe e transacao financeira para Split Payment.",
    impact:
      "Pode alterar eventos, codigos de pagamento e conciliacao para faturas de servicos de comunicacao.",
    action:
      "Validar schemas de vinculacao, cancelamento e codigos de meios de pagamento aplicaveis a NFCom.",
    changedExcerpt:
      "NT 2026.001 RTC Vinculacao Pagamento v1.01 publicada para NFCom.",
    diffBefore: "NFCom sem grupo padronizado de vinculacao financeira ao Split.",
    diffAfter: "NFCom passa a seguir a vinculacao de pagamento dos DFe.",
  },
  {
    id: "chg-dfe-tabelas-rtc-2026-06-22",
    sourceId: "dfe-svrs",
    title: "Tabelas RTC de CST, cClassTrib e credito presumido",
    protocol: "2026/0622",
    detectedAt: "2026-07-10T09:10:00-03:00",
    publicationDate: "2026-06-22",
    homologationDate: "2026-06-22",
    productionDate: "2026-06-22",
    effectiveDate: "2026-06-22",
    area: "Fiscal",
    evidence: "",
    severity: "HIGH",
    status: "IN_REVIEW",
    theme: "Tabelas fiscais",
    uf: null,
    documents: ["DF-e", "RTC", "Tabelas"],
    confidence: 90,
    summary:
      "O portal SVRS publicou tabelas atualizadas de classificacao tributaria da RT e codigos de credito presumido.",
    impact:
      "Afeta cadastros fiscais, regras de produto/servico, validacoes de XML e parametrizacao de IBS/CBS.",
    action:
      "Sincronizar tabelas com cadastros internos e criar alerta para clientes com codigos descontinuados ou alterados.",
    changedExcerpt:
      "Tabela de Codigo de Classificacao Tributaria da RT e Tabela de Codigos de Credito Presumido publicadas em 22/06/2026.",
    diffBefore: "Tabelas RTC anteriores sem ultimas atualizacoes de classificacao e credito presumido.",
    diffAfter: "Tabelas publicadas em 22/06/2026 passam a reger validacoes e cadastros.",
  },
];

export const changeSeed = [
  ...retroactiveChanges,
  {
    id: "chg-dfe-distribuicao-104",
    sourceId: "nfe-esquemas-xml",
    title: "Distribuicao de DF-e v.1.04 publicada",
    protocol: "2026/0104",
    detectedAt: "2026-07-10T09:20:00-03:00",
    publicationDate: "2026-07-03",
    homologationDate: "2026-07-03",
    productionDate: "2026-07-03",
    effectiveDate: "2026-07-03",
    area: "Desenvolvimento",
    evidence: "esquemas_xml_distribuicao_dfe_v104.zip",
    evidenceUrl:
      "https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=IzuP2y0G6hk%3D",
    severity: "CRITICAL",
    status: "IN_REVIEW",
    theme: "Distribuicao DF-e",
    uf: null,
    documents: ["DF-e", "Distribuicao DF-e", "NF-e", "XML"],
    confidence: 94,
    summary:
      "O Portal Nacional NF-e publicou o pacote de liberacao Distribuicao de DF-e v.1.04 em Esquemas XML.",
    impact:
      "Pode afetar integracoes que consomem o Web Service NFeDistribuicaoDFe, armazenamento de NSU, schemas XML e validacoes de download/manifestacao.",
    action:
      "Baixar o ZIP oficial, comparar schemas da v.1.04 com a v.1.03 e validar impactos em ambientes que consultam distribuicao de documentos fiscais eletronicos.",
    changedExcerpt:
      "Esquemas XML NF-e - Pacote de Liberacao Distribuicao de DF-e v.1.04. Publicado em 03/07/2026 (ZIP).",
    diffBefore:
      "Versoes anteriores listavam Distribuicao de DF-e v.1.03 como pacote anterior em desuso.",
    diffAfter:
      "Versoes oficiais em uso passam a listar Distribuicao de DF-e v.1.04 publicada em 03/07/2026.",
  },
  {
    id: "chg-nfe-nt-2026",
    sourceId: "nfe-notas-tecnicas",
    title: "Nota tecnica NF-e em validacao",
    protocol: "2026/0071",
    detectedAt: "2026-07-07T15:42:00-03:00",
    publicationDate: "2026-07-07",
    homologationDate: "2026-08-01",
    productionDate: "2026-09-15",
    effectiveDate: "2026-10-01",
    area: "Desenvolvimento",
    evidence: "nt_nfe_schema_2026.pdf",
    severity: "CRITICAL",
    status: "IN_REVIEW",
    theme: "Schema",
    uf: null,
    documents: ["NF-e", "NFC-e"],
    confidence: 92,
    summary:
      "A lista de conteudos tecnicos do Portal Nacional sinalizou atualizacao em pacote relacionado a nota tecnica e schemas.",
    impact:
      "Pode exigir validacao de regras de emissao, XML e homologacao antes de ativacao em producao.",
    action:
      "Fiscal e Desenvolvimento devem revisar a NT, baixar anexos oficiais e abrir tarefa de compatibilidade.",
    changedExcerpt:
      "Pacote tecnico atualizado com novo item de schema e documentacao para NF-e/NFC-e.",
    diffBefore: "Pacote anterior sem referencia a nova versao tecnica.",
    diffAfter: "Pacote tecnico atualizado com novo item de schema e documentacao.",
  },
  {
    id: "chg-sp-cbenef",
    sourceId: "sefaz-sp-cbenef",
    title: "cBenef SP precisa de conferencia",
    protocol: "2026/0074",
    detectedAt: "2026-07-07T14:20:00-03:00",
    publicationDate: "2026-05-12",
    homologationDate: "2026-06-01",
    productionDate: "2026-06-20",
    effectiveDate: "2026-07-01",
    area: "Fiscal",
    evidence: "tabela_cbenef_sp_v12.pdf",
    severity: "HIGH",
    status: "IN_REVIEW",
    theme: "cBenef",
    uf: "SP",
    documents: ["NF-e", "NFC-e"],
    confidence: 88,
    summary:
      "A pagina paulista de cBenef apresentou alteracao relevante em conteudo de orientacao e tabela.",
    impact:
      "Pode afetar cadastros fiscais, validacoes por beneficio e rejeicoes em emissao para clientes de Sao Paulo.",
    action:
      "Comparar tabela atual com cadastro interno e preparar comunicado para Suporte e Onboarding.",
    changedExcerpt:
      "Tabela e orientacoes de cBenef em Sao Paulo com atualizacao de codigos e vigencias.",
    diffBefore: "Tabela publicada com orientacoes anteriores de codigos de beneficio.",
    diffAfter: "Tabela e orientacoes com atualizacao de codigos e vigencias.",
  },
  {
    id: "chg-reforma-2026",
    sourceId: "receita-orientacoes-2026",
    title: "Orientacoes 2026 da Reforma Tributaria",
    protocol: "2026/0080",
    detectedAt: "2026-07-07T11:10:00-03:00",
    publicationDate: "2026-04-02",
    homologationDate: "2026-07-15",
    productionDate: "2026-08-20",
    effectiveDate: "2026-09-01",
    area: "Produto",
    evidence: "orientacoes_rtc_2026.pdf",
    severity: "HIGH",
    status: "PUBLISHED",
    theme: "Reforma Tributaria",
    uf: null,
    documents: ["Todos"],
    confidence: 85,
    summary:
      "A Receita atualizou orientacoes para 2026 envolvendo transicao de IBS, CBS e Imposto Seletivo.",
    impact:
      "Exige acompanhamento fiscal e planejamento de backlog de produto para campos, regras e treinamento.",
    action: "Manter acompanhamento semanal e consolidar impactos por modulo fiscal.",
    changedExcerpt:
      "Conteudo dedicado a orientacoes 2026 da Reforma Tributaria e pontos de transicao.",
    diffBefore: "Orientacoes gerais sem pagina especifica para 2026.",
    diffAfter: "Conteudo dedicado a orientacoes 2026 e pontos de transicao.",
  },
  {
    id: "chg-nfse-docs",
    sourceId: "nfse-documentacao",
    title: "Documentacao tecnica NFS-e alterada",
    protocol: "2026/0090",
    detectedAt: "2026-07-06T17:30:00-03:00",
    publicationDate: "2026-07-06",
    homologationDate: "2026-08-05",
    productionDate: "",
    effectiveDate: "",
    area: "Produto",
    evidence: "",
    severity: "MEDIUM",
    status: "DRAFT",
    theme: "Leiaute",
    uf: null,
    documents: ["NFS-e"],
    confidence: 76,
    summary:
      "Foram detectadas mudancas em links de documentacao tecnica do ambiente nacional da NFS-e.",
    impact:
      "Pode alterar exemplos, bibliotecas ou orientacoes de integracao para municipios conveniados.",
    action: "Validar se houve troca de versao de leiaute antes de publicar aviso externo.",
    changedExcerpt:
      "Lista de documentos tecnicos da NFS-e Nacional com novo link e ajuste de nomenclatura.",
    diffBefore: "Lista de documentos tecnicos anterior.",
    diffAfter: "Lista de documentos com novo link e ajuste de nomenclatura.",
  },
  {
    id: "chg-sped-institucional",
    sourceId: "sped-portal",
    title: "Ajuste institucional no Portal SPED",
    protocol: "2026/0094",
    detectedAt: "2026-07-06T09:15:00-03:00",
    publicationDate: "2026-06-01",
    homologationDate: "2026-10-01",
    productionDate: "2026-12-01",
    effectiveDate: "2027-01-01",
    area: "Fiscal",
    evidence: "guia_pratico_efd_323.pdf",
    severity: "LOW",
    status: "IGNORED",
    theme: "Outro",
    uf: null,
    documents: ["SPED Fiscal"],
    confidence: 65,
    summary:
      "Mudanca visual e de navegacao sem indicio de alteracao em guia pratico ou tabela.",
    impact: "Sem impacto operacional identificado para emissao ou obrigacao acessoria.",
    action: "Manter historico e ignorar a mudanca.",
    changedExcerpt:
      "Bloco institucional de noticias reorganizado, sem mudanca tecnica fiscal identificada.",
    diffBefore: "Bloco de noticias em ordem anterior.",
    diffAfter: "Bloco de noticias reorganizado.",
  },
];

const legacyCalendarSeed = [
  {
    id: "cal-nfse-danfse-api",
    title: "Corte API antiga DANFSe",
    date: "2026-07-15",
    severity: "CRITICAL",
    status: "IN_PROGRESS",
    uf: null,
    documents: ["NFS-e", "DANFSe"],
    sourceId: "nfse-documentacao",
  },
  {
    id: "cal-cnpj-alfanumerico-producao",
    title: "CNPJ alfanumerico em novas inscricoes",
    date: "2026-07-01",
    severity: "CRITICAL",
    status: "IN_PROGRESS",
    uf: null,
    documents: ["Cadastros", "Integracoes", "XML"],
    sourceId: "receita-cnpj-alfanumerico",
  },
  {
    id: "cal-nfse-simples-emissor-nacional",
    title: "Obrigatoriedade NFS-e Simples Nacional",
    date: "2026-09-01",
    severity: "HIGH",
    status: "PLANNED",
    uf: null,
    documents: ["NFS-e", "Simples Nacional"],
    sourceId: "nfse-nacional",
  },
  {
    id: "cal-nfe-cnpj-schema",
    title: "Validar schemas CNPJ alfanumerico NF-e",
    date: "2026-07-11",
    severity: "CRITICAL",
    status: "IN_PROGRESS",
    uf: null,
    documents: ["NF-e", "NFC-e", "XML"],
    sourceId: "nfe-esquemas-xml",
  },
  {
    id: "cal-nfe-rtc-v150",
    title: "Triagem NT 2025.002 v1.50 NF-e/NFC-e",
    date: "2026-07-12",
    severity: "CRITICAL",
    status: "IN_PROGRESS",
    uf: null,
    documents: ["NF-e", "NFC-e", "RTC"],
    sourceId: "nfe-notas-tecnicas",
  },
  {
    id: "cal-nfe-paa-2026-001",
    title: "Analise PAA NF-e/NFC-e",
    date: "2026-07-16",
    severity: "HIGH",
    status: "PLANNED",
    uf: null,
    documents: ["NF-e", "NFC-e", "PAA"],
    sourceId: "nfe-notas-tecnicas",
  },
  {
    id: "cal-dfe-tabelas-rtc",
    title: "Sincronizar tabelas RTC",
    date: "2026-07-17",
    severity: "HIGH",
    status: "PLANNED",
    uf: null,
    documents: ["DF-e", "RTC", "Tabelas"],
    sourceId: "dfe-svrs",
  },
  {
    id: "cal-cte-rtc-2026-002",
    title: "Validar CT-e RTC 2026.002",
    date: "2026-07-20",
    severity: "HIGH",
    status: "PLANNED",
    uf: null,
    documents: ["CT-e", "CT-e OS", "RTC"],
    sourceId: "cte-notas-tecnicas",
  },
  {
    id: "cal-mdfe-ciot-2026",
    title: "Validar CIOT no MDF-e",
    date: "2026-07-21",
    severity: "HIGH",
    status: "PLANNED",
    uf: null,
    documents: ["MDF-e", "CIOT"],
    sourceId: "mdfe-documentos",
  },
  {
    id: "cal-nfcom-rtc-2026-002",
    title: "Validar NFCom RTC 2026.002",
    date: "2026-07-23",
    severity: "HIGH",
    status: "PLANNED",
    uf: null,
    documents: ["NFCom", "RTC"],
    sourceId: "nfcom-svrs-documentos",
  },
  {
    id: "cal-dfe-split-payment",
    title: "Validar Split Payment nos DFe",
    date: "2026-07-24",
    severity: "HIGH",
    status: "PLANNED",
    uf: null,
    documents: ["DF-e", "CT-e", "NFCom", "BP-e", "NF3e"],
    sourceId: "dfe-svrs",
  },
  {
    id: "cal-dfe-distribuicao-104",
    title: "Validar Distribuicao DF-e v.1.04",
    date: "2026-07-10",
    severity: "CRITICAL",
    status: "IN_PROGRESS",
    uf: null,
    documents: ["DF-e", "Distribuicao DF-e", "XML"],
    sourceId: "nfe-esquemas-xml",
  },
  {
    id: "cal-reforma-2026",
    title: "Revisao orientacoes RTC 2026",
    date: "2026-07-15",
    severity: "HIGH",
    status: "PLANNED",
    uf: null,
    documents: ["Todos"],
    sourceId: "receita-orientacoes-2026",
  },
  {
    id: "cal-cnpj-alfanumerico",
    title: "Impacto CNPJ alfanumerico",
    date: "2026-07-18",
    severity: "HIGH",
    status: "IN_PROGRESS",
    uf: null,
    documents: ["Cadastros", "XML"],
    sourceId: "receita-cnpj-alfanumerico",
  },
  {
    id: "cal-sp-cbenef",
    title: "Conferencia cBenef SP",
    date: "2026-07-10",
    severity: "HIGH",
    status: "IN_PROGRESS",
    uf: "SP",
    documents: ["NF-e", "NFC-e"],
    sourceId: "sefaz-sp-cbenef",
  },
  {
    id: "cal-nt-nfe",
    title: "Triagem NT NF-e",
    date: "2026-07-08",
    severity: "CRITICAL",
    status: "IN_PROGRESS",
    uf: null,
    documents: ["NF-e", "NFC-e"],
    sourceId: "nfe-notas-tecnicas",
  },
  {
    id: "cal-nfse",
    title: "Validacao NFS-e Nacional",
    date: "2026-07-22",
    severity: "MEDIUM",
    status: "PLANNED",
    uf: null,
    documents: ["NFS-e"],
    sourceId: "nfse-documentacao",
  },
];

export const calendarSeed = changeSeed
  .filter((change) => change.status !== "IGNORED" && change.effectiveDate)
  .map((change) => ({
    id: `cal-${change.id}`,
    title: `Vigencia: ${change.title}`,
    date: change.effectiveDate,
    severity: change.severity,
    status: change.effectiveDate < "2026-07-10" ? "IN_PROGRESS" : "PLANNED",
    uf: change.uf,
    documents: change.documents,
    sourceId: change.sourceId,
    changeId: change.id,
  }));
