export const severityLabels = {
  CRITICAL: "Critica",
  HIGH: "Alta",
  MEDIUM: "Media",
  LOW: "Baixa",
};

export const statusLabels = {
  DRAFT: "Rascunho",
  IN_REVIEW: "Em analise",
  PUBLISHED: "Publicado",
  IGNORED: "Ignorado",
};

export const frequencyLabels = {
  HOURLY: "Horaria",
  DAILY: "Diaria",
  WEEKLY: "Semanal",
  MANUAL: "Manual",
};

function hashFrom(id) {
  return id.replace(/[^a-z0-9]/gi, "").slice(0, 6).padEnd(6, "0").toLowerCase();
}

function source({
  id,
  name,
  agency,
  uf = null,
  category,
  documents,
  url,
  frequency = "DAILY",
  severity = "MEDIUM",
  mode = "HTML_TEXT",
  checked = "2026-07-07T07:00:00-03:00",
}) {
  return {
    id,
    name,
    agency,
    uf,
    category,
    documents,
    url,
    frequency,
    severity,
    mode,
    active: true,
    lastCheckedAt: checked,
    lastHash: hashFrom(id),
  };
}

const nationalSources = [
  source({
    id: "nfe-portal",
    name: "NF-e/NFC-e - Portal Nacional",
    agency: "Portal Nacional NF-e",
    category: "NACIONAL",
    documents: ["NF-e", "NFC-e"],
    url: "https://www.nfe.fazenda.gov.br/portal/principal.aspx",
    frequency: "HOURLY",
    severity: "HIGH",
    checked: "2026-07-07T16:00:00-03:00",
  }),
  source({
    id: "nfe-notas-tecnicas",
    name: "NF-e/NFC-e - Notas Tecnicas",
    agency: "Portal Nacional NF-e",
    category: "NACIONAL",
    documents: ["NF-e", "NFC-e"],
    url: "https://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=04BIflQt1aY%3D",
    frequency: "HOURLY",
    severity: "CRITICAL",
    checked: "2026-07-07T16:08:00-03:00",
  }),
  source({
    id: "nfe-esquemas-xml",
    name: "NF-e - Esquemas XML",
    agency: "Portal Nacional NF-e",
    category: "NACIONAL",
    documents: ["NF-e", "DF-e", "Distribuicao DF-e", "XML"],
    url: "https://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=BMPFMBoln3w%3D",
    frequency: "HOURLY",
    severity: "CRITICAL",
    checked: "2026-07-10T09:20:00-03:00",
  }),
  source({
    id: "cte-portal",
    name: "CT-e - Portal Nacional",
    agency: "Portal Nacional CT-e",
    category: "NACIONAL",
    documents: ["CT-e", "CT-e OS", "GTV-e"],
    url: "https://www.cte.fazenda.gov.br/portal/",
    frequency: "HOURLY",
    severity: "HIGH",
    checked: "2026-07-07T15:50:00-03:00",
  }),
  source({
    id: "cte-notas-tecnicas",
    name: "CT-e - Notas Tecnicas",
    agency: "Portal Nacional CT-e",
    category: "NACIONAL",
    documents: ["CT-e", "CT-e OS"],
    url: "https://www.cte.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=Y0nErnoZpsg%3D",
    frequency: "HOURLY",
    severity: "HIGH",
    checked: "2026-07-07T15:48:00-03:00",
  }),
  source({
    id: "mdfe-svrs",
    name: "MDF-e - SVRS",
    agency: "SVRS",
    category: "NACIONAL",
    documents: ["MDF-e"],
    url: "https://dfe-portal.svrs.rs.gov.br/Mdfe",
    frequency: "HOURLY",
    severity: "HIGH",
    checked: "2026-07-07T16:05:00-03:00",
  }),
  source({
    id: "mdfe-documentos",
    name: "MDF-e - Documentos",
    agency: "SVRS",
    category: "NACIONAL",
    documents: ["MDF-e"],
    url: "https://dfe-portal.svrs.rs.gov.br/Mdfe/Documentos",
    frequency: "HOURLY",
    severity: "HIGH",
    checked: "2026-07-07T15:40:00-03:00",
  }),
  source({
    id: "dfe-svrs",
    name: "Portal DF-e SVRS",
    agency: "SVRS",
    category: "NACIONAL",
    documents: ["DF-e"],
    url: "https://dfe-portal.svrs.rs.gov.br/",
  }),
  source({
    id: "nfse-nacional",
    name: "NFS-e Nacional",
    agency: "Gov.br NFS-e",
    category: "NACIONAL",
    documents: ["NFS-e"],
    url: "https://www.gov.br/nfse/pt-br",
    severity: "HIGH",
  }),
  source({
    id: "nfse-documentacao",
    name: "NFS-e - Documentacao Tecnica",
    agency: "Gov.br NFS-e",
    category: "NACIONAL",
    documents: ["NFS-e"],
    url: "https://www.gov.br/nfse/pt-br/biblioteca/documentacao-tecnica",
    severity: "HIGH",
  }),
  source({
    id: "receita-reforma-tributaria",
    name: "Receita - Reforma Tributaria do Consumo",
    agency: "Receita Federal",
    category: "NACIONAL",
    documents: ["Todos"],
    url: "https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/acoes-e-programas/programas-e-atividades/reforma-tributaria-do-consumo",
    severity: "HIGH",
  }),
  source({
    id: "receita-orientacoes-2026",
    name: "Receita - Orientacoes 2026",
    agency: "Receita Federal",
    category: "NACIONAL",
    documents: ["Todos"],
    url: "https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/acoes-e-programas/programas-e-atividades/reforma-tributaria-do-consumo/orientacoes-2026",
    severity: "HIGH",
  }),
  source({
    id: "receita-cnpj-alfanumerico",
    name: "Receita - CNPJ Alfanumerico",
    agency: "Receita Federal",
    category: "NACIONAL",
    documents: ["Cadastros", "XML", "Integracoes"],
    url: "https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/acoes-e-programas/programas-e-atividades/cnpj-alfanumerico",
    severity: "HIGH",
  }),
  source({
    id: "confaz-ajustes-sinief",
    name: "CONFAZ - Ajustes SINIEF",
    agency: "CONFAZ",
    category: "NACIONAL",
    documents: ["DF-e"],
    url: "https://www.confaz.fazenda.gov.br/legislacao/ajustes",
    severity: "HIGH",
  }),
  source({
    id: "confaz-convenios-icms",
    name: "CONFAZ - Convenios ICMS",
    agency: "CONFAZ",
    category: "NACIONAL",
    documents: ["ICMS", "Beneficios"],
    url: "https://www.confaz.fazenda.gov.br/legislacao/convenios",
  }),
  source({
    id: "sped-portal",
    name: "Portal SPED",
    agency: "SPED",
    category: "OBRIGACAO_ACESSORIA",
    documents: ["SPED Fiscal"],
    url: "https://www.gov.br/sped/pt-br",
  }),
  source({
    id: "efd-icms-ipi",
    name: "EFD ICMS/IPI",
    agency: "SPED",
    category: "OBRIGACAO_ACESSORIA",
    documents: ["SPED Fiscal"],
    url: "https://www.gov.br/sped/pt-br/assuntos/escrituracao-fiscal-digital-efd",
  }),
  source({
    id: "nfcom-receita",
    name: "NFCom - Receita Federal",
    agency: "Receita Federal",
    category: "NACIONAL",
    documents: ["NFCom"],
    url: "https://www.gov.br/receitafederal/pt-br/assuntos/empresas-e-negocios/dfe/nfcom",
    frequency: "WEEKLY",
  }),
];

const stateRows = [
  ["sefaz-ac", "SEFAZ Acre - DF-e", "SEFAZ Acre", "AC", ["DF-e"], "https://dfe.sefaz.ac.gov.br/"],
  ["sefaz-al", "SEFAZ Alagoas - Contribuinte", "SEFAZ Alagoas", "AL", ["DF-e", "ICMS"], "https://contribuinte.sefaz.al.gov.br/"],
  ["sefaz-ap", "SEFAZ Amapa - Documentos Fiscais", "SEFAZ Amapa", "AP", ["NF-e", "NFC-e", "CT-e", "MDF-e", "EFD"], "https://www.sefaz.ap.gov.br/"],
  ["sefaz-am", "SEFAZ Amazonas - NF-e", "SEFAZ Amazonas", "AM", ["NF-e"], "https://sistemas.sefaz.am.gov.br/nfeweb/portal/index.do"],
  ["sefaz-ba", "SEFAZ Bahia - NF-e", "SEFAZ Bahia", "BA", ["NF-e"], "https://www.sefaz.ba.gov.br/inspetoria-eletronica/icms/documentos-fiscais/nota-fiscal-eletronica/"],
  ["sefaz-ce", "SEFAZ Ceara - NF-e/NFC-e", "SEFAZ Ceara", "CE", ["NF-e", "NFC-e"], "https://nfe.sefaz.ce.gov.br/pages/index.jsf"],
  ["receita-df", "Receita DF - Carta de Servicos", "Receita DF", "DF", ["DF-e"], "https://www.receita.fazenda.df.gov.br/aplicacoes/CartaServicos/"],
  ["sefaz-es", "SEFAZ Espirito Santo - NF-e", "SEFAZ Espirito Santo", "ES", ["NF-e"], "https://sefaz.es.gov.br/nfe-nota-fiscal-eletronica"],
  ["sefaz-go", "Economia Goias - NF-e", "Economia Goias", "GO", ["NF-e", "NFC-e", "CT-e", "XML"], "https://nfe.sefaz.go.gov.br/nfeweb/portal/index.jsp"],
  ["sefaz-ma", "SEFAZ Maranhao - Plataforma", "SEFAZ Maranhao", "MA", ["DF-e"], "https://plataforma.sefaz.ma.gov.br/"],
  ["sefaz-mt", "SEFAZ Mato Grosso - NF-e", "SEFAZ Mato Grosso", "MT", ["NF-e"], "https://www.sefaz.mt.gov.br/portal/nfe/"],
  ["sefaz-ms", "SEFAZ Mato Grosso do Sul - NF-e", "SEFAZ Mato Grosso do Sul", "MS", ["NF-e"], "https://www.nfe.ms.gov.br/"],
  ["sefaz-mg", "SEF Minas Gerais - Documentos Fiscais", "SEF Minas Gerais", "MG", ["NF-e", "DF-e"], "https://www.fazenda.mg.gov.br/empresas/documentos_fiscais/"],
  ["sefa-pa", "SEFA Para - Servicos", "SEFA Para", "PA", ["DF-e"], "https://app.sefa.pa.gov.br/pservicos/"],
  ["sefaz-pb", "SEFAZ Paraiba - NF-e", "SEFAZ Paraiba", "PB", ["NF-e"], "https://www.sefaz.pb.gov.br/info/notas-fiscais/nf-e"],
  ["sefaz-pr", "Fazenda Parana - NF-e", "Fazenda Parana", "PR", ["NF-e"], "https://sped.fazenda.pr.gov.br/NFe"],
  ["sefaz-pe", "SEFAZ Pernambuco - Documentos Fiscais", "SEFAZ Pernambuco", "PE", ["NF-e", "DF-e"], "https://www.sefaz.pe.gov.br/Servicos/ICMS/Paginas/Documentos_Fiscais.aspx"],
  ["sefaz-pi", "SEFAZ Piaui - Documentos Eletronicos", "SEFAZ Piaui", "PI", ["NF-e", "NFC-e", "CT-e", "MDF-e", "EFD"], "https://portal.sefaz.pi.gov.br/conteudos-institucional%2Bdocumentos-eletronicos%2B69d6979dc41c7a09017fa749"],
  ["sefaz-rj", "SEFAZ Rio de Janeiro - DF-e", "SEFAZ Rio de Janeiro", "RJ", ["DF-e", "Beneficios"], "https://portal.fazenda.rj.gov.br/dfe/"],
  ["sefaz-rn", "SEFAZ Rio Grande do Norte - Documentos Eletronicos", "SEFAZ Rio Grande do Norte", "RN", ["NF-e", "NFC-e", "CT-e", "BP-e", "MDF-e", "NFA", "EFD"], "https://www.sefaz.rn.gov.br/postagem/documentos-eletronicos/"],
  ["sefaz-rs", "SEFAZ RS / SVRS - DF-e", "SEFAZ RS / SVRS", "RS", ["DF-e"], "https://dfe-portal.svrs.rs.gov.br/", "HOURLY", "HIGH"],
  ["sefin-ro", "SEFIN Rondonia - NF-e", "SEFIN Rondonia", "RO", ["NF-e"], "https://www.sefin.ro.gov.br/conteudo.jsp?idCategoria=524"],
  ["sefaz-rr", "SEFAZ Roraima - Portal", "SEFAZ Roraima", "RR", ["DF-e"], "https://www.sefaz.rr.gov.br/"],
  ["sefaz-sc", "SEF Santa Catarina - NF-e", "SEF Santa Catarina", "SC", ["NF-e", "NFC-e"], "https://www.sef.sc.gov.br/servicos/servico/62/NF-e_-_Nota_Fiscal_Eletr%25C3%25B4nica"],
  ["sefaz-sp-cbenef", "SEFAZ Sao Paulo - cBenef", "SEFAZ Sao Paulo", "SP", ["NF-e", "NFC-e"], "https://portal.fazenda.sp.gov.br/servicos/nfe/Paginas/cBenef.aspx", "HOURLY", "HIGH"],
  ["sefaz-se", "SEFAZ Sergipe - Servicos Online", "SEFAZ Sergipe", "SE", ["DF-e"], "https://www.sefaz.se.gov.br/SitePages/servicos-online.aspx"],
  ["sefaz-to", "SEFAZ Tocantins - Documentos Fiscais Eletronicos", "SEFAZ Tocantins", "TO", ["DF-e", "EFD"], "https://www.to.gov.br/sefaz/documentos-fiscais-eletronicos/2fowj6ej5zil"],
];

const stateSources = stateRows.map(
  ([id, name, agency, uf, documents, url, frequency = "DAILY", severity = "MEDIUM"], index) =>
    source({
      id,
      name,
      agency,
      uf,
      category: "ESTADUAL",
      documents,
      url,
      frequency,
      severity,
      checked: `2026-07-07T${String(6 + Math.floor(index / 2)).padStart(2, "0")}:${String(
        (index * 7) % 60,
      ).padStart(2, "0")}:00-03:00`,
    }),
);

export const sourceSeed = [...nationalSources, ...stateSources];

export const changeSeed = [
  {
    id: "chg-dfe-distribuicao-104",
    sourceId: "nfe-esquemas-xml",
    title: "Distribuicao de DF-e v.1.04 publicada",
    protocol: "2026/0104",
    detectedAt: "2026-07-10T09:20:00-03:00",
    publicationDate: "2026-07-03",
    homologationDate: "2026-07-03",
    productionDate: "2026-07-03",
    effectiveDate: "2026-07-03",
    area: "Desenvolvimento",
    evidence: "esquemas_xml_distribuicao_dfe_v104.zip",
    severity: "CRITICAL",
    status: "IN_REVIEW",
    theme: "Distribuicao DF-e",
    uf: null,
    documents: ["DF-e", "Distribuicao DF-e", "NF-e", "XML"],
    confidence: 94,
    summary:
      "O Portal Nacional NF-e publicou o pacote de liberacao Distribuicao de DF-e v.1.04 em Esquemas XML.",
    impact:
      "Pode afetar integracoes que consomem o Web Service NFeDistribuicaoDFe, armazenamento de NSU, schemas XML e validacoes de download/manifestacao.",
    action:
      "Baixar o ZIP oficial, comparar schemas da v.1.04 com a v.1.03 e validar impactos em ambientes que consultam distribuicao de documentos fiscais eletronicos.",
    changedExcerpt:
      "Esquemas XML NF-e - Pacote de Liberacao Distribuicao de DF-e v.1.04. Publicado em 03/07/2026 (ZIP).",
    diffBefore:
      "Versoes anteriores listavam Distribuicao de DF-e v.1.03 como pacote anterior em desuso.",
    diffAfter:
      "Versoes oficiais em uso passam a listar Distribuicao de DF-e v.1.04 publicada em 03/07/2026.",
  },
  {
    id: "chg-nfe-nt-2026",
    sourceId: "nfe-notas-tecnicas",
    title: "Nota tecnica NF-e em validacao",
    protocol: "2026/0071",
    detectedAt: "2026-07-07T15:42:00-03:00",
    publicationDate: "2026-07-07",
    homologationDate: "2026-08-01",
    productionDate: "2026-09-15",
    effectiveDate: "2026-10-01",
    area: "Desenvolvimento",
    evidence: "nt_nfe_schema_2026.pdf",
    severity: "CRITICAL",
    status: "IN_REVIEW",
    theme: "Schema",
    uf: null,
    documents: ["NF-e", "NFC-e"],
    confidence: 92,
    summary:
      "A lista de conteudos tecnicos do Portal Nacional sinalizou atualizacao em pacote relacionado a nota tecnica e schemas.",
    impact:
      "Pode exigir validacao de regras de emissao, XML e homologacao antes de ativacao em producao.",
    action:
      "Fiscal e Desenvolvimento devem revisar a NT, baixar anexos oficiais e abrir tarefa de compatibilidade.",
    changedExcerpt:
      "Pacote tecnico atualizado com novo item de schema e documentacao para NF-e/NFC-e.",
    diffBefore: "Pacote anterior sem referencia a nova versao tecnica.",
    diffAfter: "Pacote tecnico atualizado com novo item de schema e documentacao.",
  },
  {
    id: "chg-sp-cbenef",
    sourceId: "sefaz-sp-cbenef",
    title: "cBenef SP precisa de conferencia",
    protocol: "2026/0074",
    detectedAt: "2026-07-07T14:20:00-03:00",
    publicationDate: "2026-05-12",
    homologationDate: "2026-06-01",
    productionDate: "2026-06-20",
    effectiveDate: "2026-07-01",
    area: "Fiscal",
    evidence: "tabela_cbenef_sp_v12.pdf",
    severity: "HIGH",
    status: "IN_REVIEW",
    theme: "cBenef",
    uf: "SP",
    documents: ["NF-e", "NFC-e"],
    confidence: 88,
    summary:
      "A pagina paulista de cBenef apresentou alteracao relevante em conteudo de orientacao e tabela.",
    impact:
      "Pode afetar cadastros fiscais, validacoes por beneficio e rejeicoes em emissao para clientes de Sao Paulo.",
    action:
      "Comparar tabela atual com cadastro interno e preparar comunicado para Suporte e Onboarding.",
    changedExcerpt:
      "Tabela e orientacoes de cBenef em Sao Paulo com atualizacao de codigos e vigencias.",
    diffBefore: "Tabela publicada com orientacoes anteriores de codigos de beneficio.",
    diffAfter: "Tabela e orientacoes com atualizacao de codigos e vigencias.",
  },
  {
    id: "chg-reforma-2026",
    sourceId: "receita-orientacoes-2026",
    title: "Orientacoes 2026 da Reforma Tributaria",
    protocol: "2026/0080",
    detectedAt: "2026-07-07T11:10:00-03:00",
    publicationDate: "2026-04-02",
    homologationDate: "2026-07-15",
    productionDate: "2026-08-20",
    effectiveDate: "2026-09-01",
    area: "Produto",
    evidence: "orientacoes_rtc_2026.pdf",
    severity: "HIGH",
    status: "PUBLISHED",
    theme: "Reforma Tributaria",
    uf: null,
    documents: ["Todos"],
    confidence: 85,
    summary:
      "A Receita atualizou orientacoes para 2026 envolvendo transicao de IBS, CBS e Imposto Seletivo.",
    impact:
      "Exige acompanhamento fiscal e planejamento de backlog de produto para campos, regras e treinamento.",
    action: "Manter acompanhamento semanal e consolidar impactos por modulo fiscal.",
    changedExcerpt:
      "Conteudo dedicado a orientacoes 2026 da Reforma Tributaria e pontos de transicao.",
    diffBefore: "Orientacoes gerais sem pagina especifica para 2026.",
    diffAfter: "Conteudo dedicado a orientacoes 2026 e pontos de transicao.",
  },
  {
    id: "chg-nfse-docs",
    sourceId: "nfse-documentacao",
    title: "Documentacao tecnica NFS-e alterada",
    protocol: "2026/0090",
    detectedAt: "2026-07-06T17:30:00-03:00",
    publicationDate: "2026-07-06",
    homologationDate: "2026-08-05",
    productionDate: "",
    effectiveDate: "",
    area: "Produto",
    evidence: "",
    severity: "MEDIUM",
    status: "DRAFT",
    theme: "Leiaute",
    uf: null,
    documents: ["NFS-e"],
    confidence: 76,
    summary:
      "Foram detectadas mudancas em links de documentacao tecnica do ambiente nacional da NFS-e.",
    impact:
      "Pode alterar exemplos, bibliotecas ou orientacoes de integracao para municipios conveniados.",
    action: "Validar se houve troca de versao de leiaute antes de publicar aviso externo.",
    changedExcerpt:
      "Lista de documentos tecnicos da NFS-e Nacional com novo link e ajuste de nomenclatura.",
    diffBefore: "Lista de documentos tecnicos anterior.",
    diffAfter: "Lista de documentos com novo link e ajuste de nomenclatura.",
  },
  {
    id: "chg-sped-institucional",
    sourceId: "sped-portal",
    title: "Ajuste institucional no Portal SPED",
    protocol: "2026/0094",
    detectedAt: "2026-07-06T09:15:00-03:00",
    publicationDate: "2026-06-01",
    homologationDate: "2026-10-01",
    productionDate: "2026-12-01",
    effectiveDate: "2027-01-01",
    area: "Fiscal",
    evidence: "guia_pratico_efd_323.pdf",
    severity: "LOW",
    status: "IGNORED",
    theme: "Outro",
    uf: null,
    documents: ["SPED Fiscal"],
    confidence: 65,
    summary:
      "Mudanca visual e de navegacao sem indicio de alteracao em guia pratico ou tabela.",
    impact: "Sem impacto operacional identificado para emissao ou obrigacao acessoria.",
    action: "Manter historico e ignorar a mudanca.",
    changedExcerpt:
      "Bloco institucional de noticias reorganizado, sem mudanca tecnica fiscal identificada.",
    diffBefore: "Bloco de noticias em ordem anterior.",
    diffAfter: "Bloco de noticias reorganizado.",
  },
];

export const calendarSeed = [
  {
    id: "cal-dfe-distribuicao-104",
    title: "Validar Distribuicao DF-e v.1.04",
    date: "2026-07-10",
    severity: "CRITICAL",
    status: "IN_PROGRESS",
    uf: null,
    documents: ["DF-e", "Distribuicao DF-e", "XML"],
    sourceId: "nfe-esquemas-xml",
  },
  {
    id: "cal-reforma-2026",
    title: "Revisao orientacoes RTC 2026",
    date: "2026-07-15",
    severity: "HIGH",
    status: "PLANNED",
    uf: null,
    documents: ["Todos"],
    sourceId: "receita-orientacoes-2026",
  },
  {
    id: "cal-cnpj-alfanumerico",
    title: "Impacto CNPJ alfanumerico",
    date: "2026-07-18",
    severity: "HIGH",
    status: "IN_PROGRESS",
    uf: null,
    documents: ["Cadastros", "XML"],
    sourceId: "receita-cnpj-alfanumerico",
  },
  {
    id: "cal-sp-cbenef",
    title: "Conferencia cBenef SP",
    date: "2026-07-10",
    severity: "HIGH",
    status: "IN_PROGRESS",
    uf: "SP",
    documents: ["NF-e", "NFC-e"],
    sourceId: "sefaz-sp-cbenef",
  },
  {
    id: "cal-nt-nfe",
    title: "Triagem NT NF-e",
    date: "2026-07-08",
    severity: "CRITICAL",
    status: "IN_PROGRESS",
    uf: null,
    documents: ["NF-e", "NFC-e"],
    sourceId: "nfe-notas-tecnicas",
  },
  {
    id: "cal-nfse",
    title: "Validacao NFS-e Nacional",
    date: "2026-07-22",
    severity: "MEDIUM",
    status: "PLANNED",
    uf: null,
    documents: ["NFS-e"],
    sourceId: "nfse-documentacao",
  },
];
